obj-$(CONFIG_CONNECTAL)		+= connectal.o connectal-drv.o generated/portal.o generated/transportHardware.o
obj-$(CONFIG_CONNECTAL_CONSOLE)	+= connectal-con.o generated/SerialRequest.o generated/SerialIndication.o
obj-$(CONFIG_CONNECTAL_BLOCK)	+= connectal-blk.o generated/BlockDevRequest.o generated/BlockDevResponse.o
obj-$(CONFIG_CONNECTAL_RFB)	+= connectal-rfb.o
