obj-$(CONFIG_CONNECTAL)		+= connectal.o connectal-drv.o
obj-$(CONFIG_CONNECTAL_CONSOLE)	+= connectal-con.o
obj-$(CONFIG_CONNECTAL_BLOCK)	+= connectal-blk.o
obj-$(CONFIG_CONNECTAL_RFB)	+= connectal-rfb.o
